### ISSUE TITLE
Missing 'for' loop condition and start bracket

### ISSUE THREAD

**Issue by shreyadimri** [Yefeng0920/BRMA_tutorial_git#1]
Heya, 
Was trying to run through the tutorial, thanks for it, very descriptive. 
I noticed a minor bug when running the code:
Missing `for` loop condition in the sensitivity analysis of rho parameters for lnRR (Conduct the sensitivity analysis on lnRR
) and SMD(Conduct the sensitivity analysis on SMD) in Multi-level meta-analysis of lnRR with SMD

```
for (i in 1:length(rho_range))
{
```

**Comment by Yefeng0920** [comment]
Hey @shreyadimri,
Awesome! Good spotting and thanks for your interest. I fixed it now

Cheers,
Yefeng
